development:
  name: Statusify
  theme: <%= ENV['STATUSIFY_THEME' || 'light' %>

test:
  name: Statusify
  theme: <%= ENV['STATUSIFY_THEME' || 'light' %>

production:
  name: Statusify
  theme: <%= ENV['STATUSIFY_THEME'] || 'light' %>