development:
  name: <%= (ENV['APP_NAME'] || 'statusify').capitalize! %>
  theme: <%= ENV['STATUSIFY_THEME'] || 'light' %>

test:
  name: <%= (ENV['APP_NAME'] || 'statusify').capitalize! %>
  theme: <%= ENV['STATUSIFY_THEME'] || 'light' %>

production:
  name: <%= (ENV['APP_NAME'] || 'statusify').capitalize! %>
  theme: <%= ENV['STATUSIFY_THEME'] || 'light' %>
