development:
  name: <%= (ENV['APP_NAME'] || 'statusify').capitalize! %>
  theme: <%= ENV['STATUSIFY_THEME'] || 'light' %>
  mail_from: root@localhost

test:
  name: <%= (ENV['APP_NAME'] || 'statusify').capitalize! %>
  theme: <%= ENV['STATUSIFY_THEME'] || 'light' %>
  mail_from: root@localhost

production:
  name: <%= (ENV['APP_NAME'] || 'statusify').capitalize! %>
  theme: <%= ENV['STATUSIFY_THEME'] || 'light' %>
  mail_from: 'Set this'